apiVersion: v1
kind: Service
metadata:
  name: web1
  labels:
    code: html
spec:
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80
  selector:
    code: html 
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  labels:
    code: html
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web1
  labels:
    code: html
spec:
  selector:
    matchLabels:
      code: html
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        code: html
        tier: frontend
    spec:
      containers:
      - image: httpd
        name: web1con
        
        ports:
        - containerPort: 80
          name: web1con
        volumeMounts:
        - name: persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim
